// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using MockSrv.Application.Interfaces.DbContextes;
using MockSrv.Domain.Entities;

namespace MockSrv.Persistence.DbContexts;

public partial class ApplicationDbContext : DbContext, IApplicationDbContext
{
    public virtual DbSet<MockEntity> MockRequests { get; set; }

    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.EnableDetailedErrors();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MockEntity>(entity =>
        {
            entity
                .Property(e => e.HashKey)
                .HasComputedColumnSql("([RequestPath] || [RequestMethod] || IFNULL([RequestHeaders], '') || IFNULL([RequestQueryString], '') || IFNULL([RequestBody], ''))", true);

            entity
                .HasIndex(u => u.HashKey)
                .IsUnique();
        });

        // modelBuilder.UseCollation("NOCASE"); // Non fonctionnelle avec une base de données mémoire.
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

