//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockSrv.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MockSrv.Web.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Api.
        /// </summary>
        public static string ApiNameDisplay {
            get {
                return ResourceManager.GetString("ApiNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Route.
        /// </summary>
        public static string ApiRouteDisplay {
            get {
                return ResourceManager.GetString("ApiRouteDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Body.
        /// </summary>
        public static string RequestBodyDisplay {
            get {
                return ResourceManager.GetString("RequestBodyDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Headers.
        /// </summary>
        public static string RequestHeadersDisplay {
            get {
                return ResourceManager.GetString("RequestHeadersDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Headers invalids.
        /// </summary>
        public static string RequestHeadersInvalid {
            get {
                return ResourceManager.GetString("RequestHeadersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Method.
        /// </summary>
        public static string RequestMethodDisplay {
            get {
                return ResourceManager.GetString("RequestMethodDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path.
        /// </summary>
        public static string RequestPathDisplay {
            get {
                return ResourceManager.GetString("RequestPathDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path invalid.
        /// </summary>
        public static string RequestPathInvalid {
            get {
                return ResourceManager.GetString("RequestPathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Querystring.
        /// </summary>
        public static string RequestQueryStringDisplay {
            get {
                return ResourceManager.GetString("RequestQueryStringDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Querystring invalid.
        /// </summary>
        public static string RequestQueryStringInvalid {
            get {
                return ResourceManager.GetString("RequestQueryStringInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Body.
        /// </summary>
        public static string ResponseBodyDisplay {
            get {
                return ResourceManager.GetString("ResponseBodyDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Body does not conform to Content-Type.
        /// </summary>
        public static string ResponseBodyInvalid {
            get {
                return ResourceManager.GetString("ResponseBodyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Content-type.
        /// </summary>
        public static string ResponseContentTypeDisplay {
            get {
                return ResourceManager.GetString("ResponseContentTypeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Headers.
        /// </summary>
        public static string ResponseHeadersDisplay {
            get {
                return ResourceManager.GetString("ResponseHeadersDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Headers invalids.
        /// </summary>
        public static string ResponseHeadersInvalid {
            get {
                return ResourceManager.GetString("ResponseHeadersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à StatusCode.
        /// </summary>
        public static string ResponseStatusCodeDisplay {
            get {
                return ResourceManager.GetString("ResponseStatusCodeDisplay", resourceCulture);
            }
        }
    }
}
