// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MockSrv.Models
{
    public partial class MockRequests
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string RequestPath { get; set; }
        public string RequestMethod { get; set; }
        public string RequestQueryString { get; set; }
        public string RequestBody { get; set; }
        public string ResponseBody { get; set; }
        public int ResponseStatusCode { get; set; }
        public string ResponseContentType { get; set; }
    }
}