// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace MockSrv.Models
{
    public partial class MockSrvDbContext : DbContext
    {
        public MockSrvDbContext()
        {
        }

        public MockSrvDbContext(DbContextOptions<MockSrvDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<MockRequests> MockRequests { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}