<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Sqlite" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.10" />
    <PackageReference Include="Microsoft.AspNetCore.ResponseCompression" Version="2.3.10" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="[8.0.27, 9.0.0)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MockSrv.Analyzers\MockSrv.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\MockSrv.Application\MockSrv.Application.csproj" />
    <ProjectReference Include="..\MockSrv.Common\MockSrv.Common.csproj" />
    <ProjectReference Include="..\MockSrv.Persistence\MockSrv.Persistence.csproj" />
  </ItemGroup>

</Project>
