<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="[8.0.27, 9.0.0)" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.Collections.Immutable" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="[8.0.27, 9.0.0)" />
    <PackageReference Include="AspNetCore.HealthChecks.Sqlite" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MockSrv.Analyzers\MockSrv.Analyzers.csproj" />
    <ProjectReference Include="..\MockSrv.Api\MockSrv.Api.csproj" />
    <ProjectReference Include="..\MockSrv.Persistence\MockSrv.Persistence.csproj" />
  </ItemGroup>

</Project>